pragma circom 2.2.3;
// Generated by scripts/write-google-circuit.mjs. Development POC, unaudited.
// All 12 public signals must be checked by the authorization application.
include "./strict_jwt_primitives.circom";
include "@zk-email/circuits/lib/rsa.circom";

template GoogleJwt() {
    signal input identity[2];
    signal input keyHash[2];
    signal input audienceHash[2];
    signal input sessionKey[2];
    signal input genesisHash[2];
    signal input sessionExpiresAt;
    signal input notBefore;
    signal input message[1024];
    signal input messageLength;
    signal input headerLength;
    signal input modulus[17];
    signal input signature[17];
    signal input headerFieldCount;
    signal input headerKeyLengths[3];
    signal input headerValueLengths[3];
    signal input payloadFieldCount;
    signal input payloadKeyLengths[18];
    signal input payloadValueLengths[18];
    signal input salt[32];
    signal input randomness[32];
    signal input identityPreimage[604];
    _ <== Num2Bits(11)(messageLength);
    _ <== Num2Bits(8)(headerLength);
    signal period <== ItemAtIndex(1024)(message, headerLength);
    period === 46;
    signal payloadLength <== messageLength-headerLength-1;
    _ <== Num2Bits(10)(payloadLength);
    signal headerEncoded[128] <== SelectSubArray(1024, 128)(message, 0, headerLength);
    signal payloadEncoded[896] <== SelectSubArray(1024, 896)(message, headerLength+1, payloadLength);
    component headerDecode = StrictBase64Url(128);
    headerDecode.in <== headerEncoded;
    headerDecode.length <== headerLength;
    component payloadDecode = StrictBase64Url(896);
    payloadDecode.in <== payloadEncoded;
    payloadDecode.length <== payloadLength;
    var headerWords[3] = [6777953,6580587,7371124];
    var headerLens[3] = [3,3,3];
    var headerKinds[3] = [0,0,0];
    component header = StrictFlatJson(96, 3, 3, 96, headerWords, headerLens, headerKinds);
    header.in <== headerDecode.out;
    header.length <== headerDecode.decodedLength;
    header.fieldCount <== headerFieldCount;
    header.keyLengths <== headerKeyLengths;
    header.valueLengths <== headerValueLengths;
    for (var k = 0; k < 3; k++) header.counts[k] === 1;
    header.lengths[0] === 5;
    header.lengths[2] === 3;
    var rs256[5] = [82,83,50,53,54];
    var jwt[3] = [74,87,84];
    for (var i = 0; i < 5; i++) header.values[0][i] === rs256[i];
    for (var i = 0; i < 3; i++) header.values[2][i] === jwt[i];
    signal kidNonempty <== LessEqThan(7)([1, header.lengths[1]]);
    signal kidFits <== LessEqThan(7)([header.lengths[1], 64]);
    kidNonempty === 1;
    kidFits === 1;
    var payloadWords[18] = [7566185,7371361,6583649,6452595,25704,465624460645,2036275624513531303077744937626981,435459878766,6709870,1701667182,28554821437188464,478976730527665378191719,122618043015094461291913574,7627113,7370853,6911082,29400259778016353,1871005112020476654945];
    var payloadLens[18] = [3,3,3,3,2,5,14,5,3,4,7,10,11,3,3,3,7,9];
    var payloadKinds[18] = [0,0,0,0,0,0,2,0,1,0,0,0,0,1,1,0,0,1];
    component claims = StrictFlatJson(672, 18, 18, 255, payloadWords, payloadLens, payloadKinds);
    claims.in <== payloadDecode.out;
    claims.length <== payloadDecode.decodedLength;
    claims.fieldCount <== payloadFieldCount;
    claims.keyLengths <== payloadKeyLengths;
    claims.valueLengths <== payloadValueLengths;
    var required[6] = [0,2,3,7,13,14];
    for (var k = 0; k < 6; k++) claims.counts[required[k]] === 1;
    signal longIssuer <== IsEqual()([claims.lengths[0], 27]);
    signal abbreviatedIssuer <== IsEqual()([claims.lengths[0], 19]);
    longIssuer+abbreviatedIssuer === 1;
    var issuer[27] = [104,116,116,112,115,58,47,47,97,99,99,111,117,110,116,115,46,103,111,111,103,108,101,46,99,111,109];
    var shortIssuer[19] = [97,99,99,111,117,110,116,115,46,103,111,111,103,108,101,46,99,111,109];
    for (var i = 0; i < 27; i++) {
        if (i < 19) claims.values[0][i] === longIssuer*issuer[i]+abbreviatedIssuer*shortIssuer[i];
        else claims.values[0][i] === longIssuer*issuer[i];
    }
    signal audNonempty <== LessEqThan(9)([1, claims.lengths[2]]);
    signal subNonempty <== LessEqThan(9)([1, claims.lengths[3]]);
    audNonempty === 1;
    subNonempty === 1;
    claims.counts[1]*(claims.lengths[1]-claims.lengths[2]) === 0;
    signal audActive[255];
    signal subActive[255];
    signal audVisible[255];
    signal subVisible[255];
    for (var i = 0; i < 255; i++) {
        claims.counts[1]*(claims.values[1][i]-claims.values[2][i]) === 0;
        audActive[i] <== LessThan(9)([i, claims.lengths[2]]);
        subActive[i] <== LessThan(9)([i, claims.lengths[3]]);
        audVisible[i] <== LessEqThan(8)([33, claims.values[2][i]]);
        subVisible[i] <== LessEqThan(8)([33, claims.values[3][i]]);
        audActive[i]*(1-audVisible[i]) === 0;
        subActive[i]*(1-subVisible[i]) === 0;
    }
    // Signed time policy plus a public execution-time lower bound.
    _ <== Num2Bits(32)(sessionExpiresAt);
    signal expiryAfterIat <== LessThan(33)([claims.numbers[13], sessionExpiresAt]);
    signal sessionDuration <== LessEqThan(33)([sessionExpiresAt, claims.numbers[13]+600]);
    signal expiryInToken <== LessEqThan(32)([sessionExpiresAt, claims.numbers[14]]);
    signal tokenOrder <== LessThan(32)([claims.numbers[13], claims.numbers[14]]);
    signal tokenDuration <== LessEqThan(33)([claims.numbers[14]-claims.numbers[13], 7200]);
    signal iatSupportsSkew <== LessEqThan(32)([60, claims.numbers[13]]);
    signal nbfBeforeExpiry <== LessThan(32)([claims.numbers[8], sessionExpiresAt]);
    expiryAfterIat === 1;
    sessionDuration === 1;
    expiryInToken === 1;
    tokenOrder === 1;
    tokenDuration === 1;
    iatSupportsSkew === 1;
    nbfBeforeExpiry === 1;
    signal nbfLater <== LessThan(32)([claims.numbers[13]-60, claims.numbers[8]]);
    notBefore === claims.numbers[13]-60+nbfLater*(claims.numbers[8]-claims.numbers[13]+60);
    // Each RSA value is a canonical 2048-bit integer in 121-bit limbs.
    signal modulusBits[2057];
    signal signatureBits[2057];
    component modLimbs[17];
    component sigLimbs[17];
    for (var k = 0; k < 17; k++) {
        modLimbs[k] = Num2Bits(121);
        sigLimbs[k] = Num2Bits(121);
        modLimbs[k].in <== modulus[k];
        sigLimbs[k].in <== signature[k];
        for (var b = 0; b < 121; b++) {
            modulusBits[k*121+b] <== modLimbs[k].out[b];
            signatureBits[k*121+b] <== sigLimbs[k].out[b];
        }
    }
    modulusBits[2047] === 1;
    modulusBits[0] === 1;
    for (var i = 2048; i < 2057; i++) {
        modulusBits[i] === 0;
        signatureBits[i] === 0;
    }
    signal messageDigest[256] <== StrictSha256(1024, 1024)(message, messageLength);
    signal rsaMessage[17];
    for (var k = 0; k < 17; k++) {
        var value = 0;
        for (var b = 0; b < 121; b++) {
            if (k*121+b < 256) value += messageDigest[255-k*121-b]*(2 ** b);
        }
        rsaMessage[k] <== value;
    }
    component rsa = RSAVerifier65537(121, 17);
    rsa.message <== rsaMessage;
    rsa.modulus <== modulus;
    rsa.signature <== signature;
    signal modulusBytes[256];
    for (var i = 0; i < 256; i++) {
        var value = 0;
        for (var b = 0; b < 8; b++) value += modulusBits[(255-i)*8+b]*(1 << b);
        modulusBytes[i] <== value;
    }
    signal keyDigest[256] <== StrictSha256(256, 320)(modulusBytes, 256);
    signal audDigest[256] <== StrictSha256(255, 320)(claims.values[2], claims.lengths[2]);
    // The full identity preimage is private but every byte is constrained.
    var identityDomain[29] = [97,108,103,111,114,97,110,100,45,122,107,108,111,103,105,110,45,105,100,101,110,116,105,116,121,45,118,49,0];
    for (var i = 0; i < 29; i++) identityPreimage[i] === identityDomain[i];
    identityPreimage[29] === 0;
    identityPreimage[30] === 27;
    for (var i = 0; i < 27; i++) identityPreimage[31+i] === issuer[i];
    identityPreimage[58] === 0;
    identityPreimage[59] === claims.lengths[2];
    for (var i = 0; i < 255; i++) audActive[i]*(identityPreimage[60+i]-claims.values[2][i]) === 0;
    signal subSection[257] <== VarShiftLeft(604, 257)(identityPreimage, 60+claims.lengths[2]);
    subSection[0] === 0;
    subSection[1] === claims.lengths[3];
    for (var i = 0; i < 255; i++) subActive[i]*(subSection[i+2]-claims.values[3][i]) === 0;
    signal saltSection[32] <== VarShiftLeft(604, 32)(identityPreimage, 60+claims.lengths[2]+2+claims.lengths[3]);
    for (var i = 0; i < 32; i++) saltSection[i] === salt[i];
    signal identityLength <== 60+claims.lengths[2]+2+claims.lengths[3]+32;
    signal identityDigest[256] <== StrictSha256(604, 640)(identityPreimage, identityLength);
    signal keyBits[2][128];
    signal networkBits[2][128];
    for (var k = 0; k < 2; k++) {
        keyBits[k] <== Num2Bits(128)(sessionKey[k]);
        networkBits[k] <== Num2Bits(128)(genesisHash[k]);
    }
    signal expiryBits[64] <== Num2Bits(64)(sessionExpiresAt);
    var nonceDomain[28] = [97,108,103,111,114,97,110,100,45,122,107,108,111,103,105,110,45,115,101,115,115,105,111,110,45,118,49,0];
    signal noncePreimage[132];
    for (var i = 0; i < 28; i++) noncePreimage[i] <== nonceDomain[i];
    for (var i = 0; i < 32; i++) {
        var pubByte = 0;
        var networkByte = 0;
        for (var b = 0; b < 8; b++) {
            pubByte += keyBits[i \ 16][(15-i%16)*8+b]*(1 << b);
            networkByte += networkBits[i \ 16][(15-i%16)*8+b]*(1 << b);
        }
        noncePreimage[28+i] <== networkByte;
        noncePreimage[60+i] <== pubByte;
        _ <== Num2Bits(8)(randomness[i]);
        noncePreimage[100+i] <== randomness[i];
    }
    for (var i = 0; i < 8; i++) {
        var value = 0;
        for (var b = 0; b < 8; b++) value += expiryBits[(7-i)*8+b]*(1 << b);
        noncePreimage[92+i] <== value;
    }
    signal nonceDigest[256] <== StrictSha256(132, 192)(noncePreimage, 132);
    claims.lengths[7] === 43;
    signal nonceEncoded[44];
    for (var i = 0; i < 43; i++) nonceEncoded[i] <== claims.values[7][i];
    nonceEncoded[43] <== 0;
    component nonceDecode = StrictBase64Url(44);
    nonceDecode.in <== nonceEncoded;
    nonceDecode.length <== 43;
    nonceDecode.decodedLength === 32;
    for (var i = 0; i < 32; i++) {
        var value = 0;
        for (var b = 0; b < 8; b++) value += nonceDigest[i*8+b]*(1 << (7-b));
        nonceDecode.out[i] === value;
    }
    for (var k = 0; k < 2; k++) {
        var owner = 0;
        var fingerprint = 0;
        var aud = 0;
        for (var b = 0; b < 128; b++) {
            owner += identityDigest[k*128+b]*(2 ** (127-b));
            fingerprint += keyDigest[k*128+b]*(2 ** (127-b));
            aud += audDigest[k*128+b]*(2 ** (127-b));
        }
        identity[k] === owner;
        keyHash[k] === fingerprint;
        audienceHash[k] === aud;
    }
}
component main { public [identity, keyHash, audienceHash, sessionKey, genesisHash, sessionExpiresAt, notBefore] } = GoogleJwt();
